### ISSUE TITLE
Issue : Dlopen Expected Flat Namespace

### ISSUE THREAD

**Issue by famishedrover** [azreasoners/lpmln#2]
Running 

`lpmln-infer bird.lpmln`

after following the installation steps on macOS gives the following error. 

My initial assessment is that my gcc isn't the same version as .so. Some other sources pointed out that something maybe wrong with the setup.py as well. 

Env : 
Python 3.6.12 |Anaconda, Inc.| (default, Sep  8 2020, 17:50:39) 
[GCC Clang 10.0.0 ] on darwin

```
Traceback (most recent call last):
  File "/usr/local/bin/lpmln-infer", line 8, in <module>
    from src import processor
  File "/Users/muditverma/Downloads/lpmln/src/processor.py", line 8, in <module>
    from src import learn_sdd
  File "/Users/muditverma/Downloads/lpmln/src/learn_sdd.py", line 5, in <module>
    from src import run
  File "/Users/muditverma/Downloads/lpmln/src/run.py", line 4, in <module>
    from src import save
  File "/Users/muditverma/Downloads/lpmln/src/save.py", line 1, in <module>
    from lib import sdd as sddm
  File "/Users/muditverma/Downloads/lpmln/lib/sdd.py", line 28, in <module>
    _sdd = swig_import_helper()
  File "/Users/muditverma/Downloads/lpmln/lib/sdd.py", line 24, in swig_import_helper
    _mod = imp.load_module('_sdd', fp, pathname, description)
  File "/Users/muditverma/anaconda3/envs/krr/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/Users/muditverma/anaconda3/envs/krr/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: dlopen(/Users/muditverma/Downloads/lpmln/lib/_sdd.cpython-36m-darwin.so, 2): Symbol not found: _sdd_apply_in_vtree
  Referenced from: /Users/muditverma/Downloads/lpmln/lib/_sdd.cpython-36m-darwin.so
  Expected in: flat namespace
 in /Users/muditverma/Downloads/lpmln/lib/_sdd.cpython-36m-darwin.so
```

**Comment by azreasoners** [comment]
As written in Readme.md, we tested on Ubuntu/Linux but not on macOS.
